Myclapboard\AwardBundle\Entity\AwardTranslation:
    type: entity
    table: AwardTranslation
    uniqueConstraints:
        lookup_unique_idx:
            columns: locale, object_id, field
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        locale:
            type: string
        field:
            type: string
        content:
            type: text
    manyToOne:
        object:
            targetEntity: Myclapboard\AwardBundle\Model\AwardInterface
            inversedBy: translations
            joinColumn:
                name: object_id
                referencedColumnName: id
                onDelete: CASCADE
