Myclapboard\AwardBundle\Entity\AwardWon:
    type: entity
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        year:
            type: integer
    manyToOne:
        movie:
            targetEntity: Myclapboard\MovieBundle\Model\MovieInterface
        actor:
            targetEntity: Myclapboard\ArtistBundle\Entity\Actor
            inversedBy: awards
        director:
            targetEntity: Myclapboard\ArtistBundle\Entity\Director
            inversedBy: awards
        writer:
            targetEntity: Myclapboard\ArtistBundle\Entity\Writer
            inversedBy: awards
        award:
            targetEntity: Myclapboard\AwardBundle\Model\AwardInterface
        category:
            targetEntity: Myclapboard\AwardBundle\Model\CategoryInterface
