language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION}

script:
    - bin/phpspec run -fpretty

after_script:
    - bin/coveralls -v

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    allow_failures:
        - php: 5.3
        - php: 5.3.3
        - php: 5.6
        - php: hhvm-nightly
        - env: SYMFONY_VERSION=2.3.*
        - env: SYMFONY_VERSION=2.4.*
        - env: SYMFONY_VERSION=dev-master
