parameters:
    filmboot_artist.class.artist: Filmboot\ArtistBundle\Entity\Artist

services:
    # Managers
    filmboot_artist.manager.artist:
        class: Filmboot\ArtistBundle\Manager\ArtistManager
        arguments: ["@doctrine.orm.entity_manager",'%filmboot_artist.class.artist%']

    # Commands
    filmboot_artist.command_artists:
        class: Filmboot\ArtistBundle\Command\LoadArtistsCommand
        calls:
            - [setContainer, ["@service_container"] ]
