Myclapboard\ArtistBundle\Entity\Actor:
    type: entity
    table: MovieActor
    id:
        id:
            type: string
            generator:
                strategy: UUID
    manyToOne:
        artist:
            targetEntity: Myclapboard\ArtistBundle\Model\Interfaces\ArtistInterface
            inversedBy: actors
        movie:
            targetEntity: Myclapboard\MovieBundle\Model\Interfaces\MovieInterface
            inversedBy: cast
    oneToMany:
        awards:
            targetEntity: Myclapboard\AwardBundle\Model\Interfaces\AwardWonInterface
            mappedBy: actor
            cascade: ["persist", "remove"]
            joinColumn:
                name: actor_id
                referencedColumnName: id
                onDelete: cascade
