Myclapboard\ArtistBundle\Entity\Artist:
    type: entity
    gedmo:
        translation:
            entity: Myclapboard\ArtistBundle\Entity\ArtistTranslation
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        slug:
            type: string
            length: 100
        firstName:
            type: string
            length: 50
        lastName:
            type: string
            length: 100
        birthday:
            type: datetime
            nullable: true
        biography:
            type: text
            nullable: true
            gedmo:
                - translatable
    oneToMany:
        actors:
            targetEntity: Myclapboard\ArtistBundle\Entity\Actor
            mappedBy: artist
        directors:
            targetEntity: Myclapboard\ArtistBundle\Entity\Director
            mappedBy: artist
        writers:
            targetEntity: Myclapboard\ArtistBundle\Entity\Writer
            mappedBy: artist
        images:
            targetEntity: Myclapboard\CoreBundle\Model\ImageInterface
            mappedBy: artist
            cascade: ["persist", "remove"]
        translations:
            targetEntity: Myclapboard\ArtistBundle\Entity\ArtistTranslation
            mappedBy: object
            cascade: ["persist", "remove"]
    manyToOne:
        birthplace:
            targetEntity: JJs\Bundle\GeonamesBundle\Entity\City
