Myclapboard\ArtistBundle\Entity\Director:
    type: entity
    table: MovieDirector
    id:
        id:
            type: string
            generator:
                strategy: UUID
    manyToOne:
        artist:
            targetEntity: Myclapboard\ArtistBundle\Model\ArtistInterface
            inversedBy: directors
        movie:
            targetEntity: Myclapboard\MovieBundle\Model\MovieInterface
            inversedBy: directors
    oneToMany:
        awards:
            targetEntity: Myclapboard\AwardBundle\Model\AwardWonInterface
            mappedBy: director
            cascade: ["persist", "remove"]
            joinColumn:
                name: director_id
                referencedColumnName: id
                onDelete: cascade
