Myclapboard\ArtistBundle\Entity\Image:
    type: entity
    table: ArtistImage
    id:
        name:
            type: string
            length: 100
    manyToOne:
        artist:
            targetEntity: Myclapboard\ArtistBundle\Model\Interfaces\ArtistInterface
    lifecycleCallbacks:
        postRemove: [removeUpload]
