Myclapboard\ArtistBundle\Entity\Writer:
    type: entity
    table: MovieWriter
    id:
        id:
            type: string
            generator:
                strategy: UUID
    manyToOne:
        artist:
            targetEntity: Myclapboard\ArtistBundle\Model\Interfaces\ArtistInterface
            inversedBy: writers
        movie:
            targetEntity: Myclapboard\MovieBundle\Model\Interfaces\MovieInterface
            inversedBy: writers
    oneToMany:
        awards:
            targetEntity: Myclapboard\AwardBundle\Model\Interfaces\AwardWonInterface
            mappedBy: writer
            cascade: ["persist", "remove"]
            joinColumn:
                name: writer_id
                referencedColumnName: id
                onDelete: cascade
