Myclapboard\MovieBundle\Model\Movie:
    exclusion_policy: NONE
    properties:
        id:
            expose: true
            groups: [movielist, movie]
        slug:
            expose: true
            groups: [movielist, movie]
        title:
            expose: true
            groups: [movielist, movie]
        duration:
            expose: true
            groups: [movielist, movie]
        releaseDate:
            expose: true
            groups: [movielist, movie]
        country:
            expose: true
            groups: [movielist, movie]
        storyline:
            expose: true
            groups: [movielist, movie]
        producer:
            expose: true
            groups: [movie]
        poster:
            expose: true
            groups: [movielist, movie]
        cast:
            expose: true
            groups: [movie]
        directors:
            expose: true
            groups: [movielist, movie]
        writers:
            expose: true
            groups: [movie]
        genres:
            expose: true
            groups: [movielist, movie]
        images:
            expose: true
            groups: [movie]
