Myclapboard\MovieBundle\Model\Movie:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [movie]
        slug:
            expose: true
            groups: [movie]
        title:
            expose: true
            groups: [movie]
        duration:
            expose: true
            groups: [movie]
        year:
            expose: true
            groups: [movie]
        country:
            expose: true
            groups: [movie]
        storyline:
            expose: true
            groups: [movie]
        producer:
            expose: true
            groups: [movie]
        cast:
            expose: true
            groups: [movie]
        directors:
            expose: true
            groups: [movie]
        writers:
            expose: true
            groups: [movie]
        genres:
            expose: true
            groups: [movie]
