Myclapboard\MovieBundle\Model\Movie:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href: 
                route: get_movie
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [movieList, movie, awardList, role]
        -
            rel: movies
            href: 
                route: get_movies
                absolute: true
            exclusion:
                groups: [movie]
        -
            rel: cast
            href: 
                route: get_movies_cast
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [movieList, movie]
        -
            rel: awards
            href: 
                route: get_movies_awards
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [movieList, movie]
        -
            rel: images
            href: 
                route: get_movies_images
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [movieList, movie]
        -
            rel: reviews
            href: 
                route: get_movies_reviews
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [movieList, movie]
    properties:
        id:
            expose: true
            groups: [movieList, movie, artist, awardList, role]
        slug:
            expose: true
            groups: [movieList, movie, artist, awardList, role]
        title:
            expose: true
            groups: [movieList, movie, artist, awardList, role]
        duration:
            expose: true
            groups: [movieList, movie]
        releaseDate:
            expose: true
            groups: [movieList, movie]
        country:
            expose: true
            groups: [movieList, movie]
        storyline:
            expose: true
            groups: [movieList, movie]
        producer:
            expose: true
            groups: [movie]
        website:
            expose: true
            groups: [movie, movieList]
        poster:
            expose: true
            groups: [movieList, movie]
        cast:
            expose: true
            groups: [movie]
        directors:
            expose: true
            groups: [movieList, movie]
        writers:
            expose: true
            groups: [movie]
        genres:
            expose: true
            groups: [movieList, movie]
        awards:
            expose: true
            groups: []
        images:
            expose: true
            groups: []
        reviews:
            expose: true
            groups: []
        score:
            expose: true
            groups: [movieList, movie]
