# This file belongs to myClapboard.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Myclapboard\MovieBundle\Model\Genre:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [movieList, movie]
        slug:
            expose: true
            groups: [movieList, movie]
        name:
            expose: true
            groups: [movieList, movie]
