imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
        name: myclapboard-session
    fragments:       ~
    http_method_override: true

doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        charset: UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: yml
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: yml
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false
        resolve_target_entities:
            Myclapboard\ArtistBundle\Model\ArtistInterface: Myclapboard\ArtistBundle\Entity\Artist
            Myclapboard\ArtistBundle\Model\ImageInterface: Myclapboard\ArtistBundle\Entity\Image
            
            Myclapboard\AwardBundle\Model\AwardInterface: Myclapboard\AwardBundle\Entity\Award
            Myclapboard\AwardBundle\Model\CategoryInterface: Myclapboard\AwardBundle\Entity\Category
            
            Myclapboard\MovieBundle\Model\GenreInterface: Myclapboard\MovieBundle\Entity\Genre
            Myclapboard\MovieBundle\Model\MovieInterface: Myclapboard\MovieBundle\Entity\Movie
            Myclapboard\MovieBundle\Model\ImageInterface: Myclapboard\MovieBundle\Entity\Image
            
            Myclapboard\UserBundle\Model\UserInterface: Myclapboard\UserBundle\Entity\User

swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool: { type: memory }


fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    view:
        view_response_listener: true
        mime_types:
            jsonp: ['application/javascript; charset=UTF-8']
        jsonp_handler: ~
        formats:
            jsonp: true
            json: true


jms_serializer:
    metadata:
        auto_detection: true
        directories:
            JJsGeonamesBundle:
                namespace_prefix: "JJs\\Bundle\\GeonamesBundle"
                path: "@MyclapboardCoreBundle/Resources/config/serializer"

nelmio_api_doc: ~

sensio_framework_extra:
    view:
        annotations: false

stof_doctrine_extensions:
    default_locale: en
    orm:
        default:
          translatable: true
          tree: true
