api_docs:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix: /doc

myclapboard_artist:
    type: rest
    resource: '@MyclapboardArtistBundle/Resources/config/routing.yml'

myclapboard_core:
    type: rest
    resource: '@MyclapboardCoreBundle/Resources/config/routing.yml'

myclapboard_movie:
    type: rest
    resource: '@MyclapboardMovieBundle/Resources/config/routing.yml'

fos_oauth_server_token:
    resource: '@FOSOAuthServerBundle/Resources/config/routing/token.xml'

fos_oauth_server_authorize:
    resource: '@FOSOAuthServerBundle/Resources/config/routing/authorize.xml'

api_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: MyclapboardUserBundle:Security:login }

api_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: MyclapboardUserBundle:Security:loginCheck }
