security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: %userpass%, roles: [ 'ROLE_USER' ] }
                    admin: { password: %adminpass%, roles: [ 'ROLE_ADMIN' ] }
    
    encoders:
        Myclapboard\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:  ^/
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
