JJs\Bundle\GeonamesBundle\Entity\Country:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [movielist, movie, artistList, artist]
        code:
            expose: true
            groups: [movielist, movie, artistList, artist]
        name:
            expose: true
            groups: [movielist, movie, artistList, artist]
