JJs\Bundle\GeonamesBundle\Entity\Locality:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [movieList, movie, artistList, artist, self]
        geonameIdentifier:
            expose: true
            groups: [movieList, movie, artistList, artist, self]
        nameUtf8:
            expose: true
            groups: [movieList, movie, artistList, artist, self]
        nameAscii:
            expose: true
            groups: [movieList, movie, artistList, artist, self]
        country:
            expose: true
            groups: [movieList, movie, artistList, artist, self]
