Myclapboard\AwardBundle\Model\Award:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [movie, artist]
        name:
            expose: true
            groups: [movie, artist]
