Myclapboard\AwardBundle\Model\Category:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [movie, artist, awardList]
        name:
            expose: true
            groups: [movie, artist, awardLists]
