parameters:
#    filmboot.movie.example.class: Filmboot\MovieBundle\Example

services:
#    filmboot.movie.example:
#        class: %filmboot.movie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
