myclapboard_profile:
    type: rest
    resource: Myclapboard\UserBundle\Controller\ProfileController

myclapboard_rating:
    type: rest
    resource: Myclapboard\UserBundle\Controller\RatingController

myclapboard_review:
    type: rest
    resource: Myclapboard\UserBundle\Controller\ReviewController

myclapboard_security:
    type: rest
    resource: Myclapboard\UserBundle\Controller\SecurityController

myclapboard_user_post_register:
    type: rest
    pattern: /register
    defaults: { _controller: MyclapboardUserBundle:Registration:register }
    requirements:
        _method: POST
