parameters:
    myclapboard_user.class.user: Myclapboard\UserBundle\Entity\User

services:
    # Managers
    myclapboard_user.manager.user:
        class: Myclapboard\UserBundle\Manager\UserManager
        arguments: ['@doctrine.orm.entity_manager', '%myclapboard_user.class.user%']
