parameters:
    myclapboard_user.class.user: Myclapboard\UserBundle\Entity\User
    myclapboard_user.class.rating: Myclapboard\UserBundle\Entity\Rating
    myclapboard_user.class.review: Myclapboard\UserBundle\Entity\Review

services:
    # Authentication
    apikey_user_provider:
        class: Myclapboard\UserBundle\Security\ApiKeyUserProvider
        arguments: [@myclapboard_user.manager.user]
    apikey_authenticator:
        class:     Myclapboard\UserBundle\Security\ApiKeyAuthenticator
        arguments: [@apikey_user_provider]

    # Forms
    myclapboard_user.registration.form.type:
        class: Myclapboard\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: myclapboard_user_registration }

    # Managers
    myclapboard_user.manager.user:
        class: Myclapboard\UserBundle\Manager\UserManager
        arguments: ['@doctrine', '%myclapboard_user.class.user%']

    myclapboard_user.manager.rating:
        class: Myclapboard\UserBundle\Manager\RatingManager
        arguments: ['@doctrine', '%myclapboard_user.class.rating%']

    myclapboard_user.manager.review:
        class: Myclapboard\UserBundle\Manager\ReviewManager
        arguments: ['@doctrine', '%myclapboard_user.class.review%']
