Filmbot\AwardBundle\Entity\AwardWon:
    type: entity
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        role:
            type: RoleEnum
            nullable: true
    manyToOne:
        movie:
            targetEntity: Filmbot\MovieBundle\Model\MovieInterface
        artist:
            targetEntity: Filmbot\ArtistBundle\Model\ArtistInterface
        award:
            targetEntity: Filmbot\AwardBundle\Model\AwardInterface
