Filmbot\ArtistBundle\Entity\Actor:
    type: entity
    table: MovieActor
    id:
        artist:
            associationKey: true
        movie:
            associationKey: true
    manyToOne:
        artist:
            targetEntity: Filmbot\ArtistBundle\Model\ArtistInterface
            inversedBy: actors
        movie:
            targetEntity: Filmbot\MovieBundle\Model\MovieInterface
            inversedBy: cast
