Filmbot\ArtistBundle\Entity\Director:
    type: entity
    table: MovieDirector
    id:
        artist:
            associationKey: true
        movie:
            associationKey: true
    manyToOne:
        artist:
            targetEntity: Filmbot\ArtistBundle\Model\ArtistInterface
            inversedBy: directors
        movie:
            targetEntity: Filmbot\MovieBundle\Model\MovieInterface
            inversedBy: directors
