Filmbot\ArtistBundle\Entity\Writer:
    type: entity
    table: MovieWriter
    id:
        artist:
            associationKey: true
        movie:
            associationKey: true
    manyToOne:
        artist:
            targetEntity: Filmbot\ArtistBundle\Model\ArtistInterface
            inversedBy: writers
        movie:
            targetEntity: Filmbot\MovieBundle\Model\MovieInterface
            inversedBy: writers
