Myclapboard\CoreBundle\Entity\Image:
    type: entity
    id:
        name:
            type: string
            length: 100
    manyToOne:
        movie:
            targetEntity: Myclapboard\MovieBundle\Model\MovieInterface
        artist:
            targetEntity: Myclapboard\ArtistBundle\Model\ArtistInterface
    lifecycleCallbacks:
        postRemove: [removeUpload]
