parameters:
    myclapboard_core.image.class: Myclapboard\CoreBundle\Entity\Image

services:
    # Managers
    myclapboard_core.manager.image:
        class: Myclapboard\CoreBundle\Manager\ImageManager
