parameters:
    myclapboard_core.class.baseImage: Myclapboard\CoreBundle\Entity\BaseImage

services:
    # Managers
    myclapboard_core.manager.baseImage:
        class: Myclapboard\CoreBundle\Manager\BaseImageManager
        arguments: ['@doctrine.orm.entity_manager', '%myclapboard_core.class.baseImage%']
