parameters:
    myclapboard_core.class.image: Myclapboard\CoreBundle\Entity\Image

services:
    # Managers
    myclapboard_core.manager.image:
        class: Myclapboard\CoreBundle\Manager\ImageManager
        arguments: ['@doctrine.orm.entity_manager', '%myclapboard_core.class.image%']
