parameters:
    filmbot_award.class.award: Filmbot\AwardBundle\Entity\Award
    filmbot_award.class.awardWon: Filmbot\AwardBundle\Entity\AwardWon
    filmbot_award.class.category: Filmbot\AwardBundle\Entity\Category

services:
    # Managers
    filmbot_award.manager.award:
        class: Filmbot\AwardBundle\Manager\AwardManager
        arguments: ["@doctrine.orm.entity_manager",'%filmbot_award.class.award%']
    filmbot_award.manager.awardWon:
        class: Filmbot\AwardBundle\Manager\AwardWonManager
        arguments: ["@doctrine.orm.entity_manager",'%filmbot_award.class.awardWon%']
    filmbot_award.manager.category:
        class: Filmbot\AwardBundle\Manager\CategoryManager
        arguments: ["@doctrine.orm.entity_manager",'%filmbot_award.class.category%']

    # Commands
    filmbot_award.command_awards:
        class: Filmbot\AwardBundle\Command\LoadAwardsCommand
        calls:
            - [setContainer, ["@service_container"] ]
    filmbot_award.command_awardsWon:
        class: Filmbot\AwardBundle\Command\LoadAwardsWonCommand
        calls:
            - [setContainer, ["@service_container"] ]
    filmbot_award.command_categories:
        class: Filmbot\AwardBundle\Command\LoadCategoriesCommand
        calls:
            - [setContainer, ["@service_container"] ]
