Myclapboard\ArtistBundle\Model\Image:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href: 
                route: get_artists_images
                parameters:
                    id: expr(object.getArtist().getId())
                absolute: true
            exclusion:
                groups: []
        -
            rel: artist
            href: 
                route: get_artist
                parameters:
                    id: expr(object.getArtist().getId())
                absolute: true
            exclusion:
                groups: []
    properties:
        artist:
            expose: false
            groups: []
