Myclapboard\ArtistBundle\Model\Role:
    exclusion_policy: ALL
    relations:
        -
            rel: movie
            href: 
                route: get_movie
                parameters:
                    id: expr(object.getMovie().getId())
                absolute: true
            exclusion:
                groups: [cast, artist]
        -
            rel: artist
            href: 
                route: get_artist
                parameters:
                    id: expr(object.getArtist().getId())
                absolute: true
            exclusion:
                groups: [awardList]
    properties:
        artist:
            expose: true
            groups: [movieList, movie]
        movie:
            expose: true
            groups: [artist, role]
        awards:
            expose: true
            groups: [artist]
