Myclapboard\ArtistBundle\Model\Role:
    exclusion_policy: ALL
    properties:
        artist:
            expose: true
            groups: [movielist, movie]
        movie:
            expose: true
            groups: [artist]
        awards:
            expose: true
            groups: [movie, artist]
