Myclapboard\ArtistBundle\Model\Artist:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [movielist, movie]
        slug:
            expose: true
            groups: [movielist, movie]
        firstName:
            expose: true
            groups: [movielist, movie]
        lastName:
            expose: true
            groups: [movielist, movie]
        birthday:
            expose: true
            groups: [movielist, movie]
        birthplace:
            expose: true
            groups: [movielist, movie]
        biography:
            expose: true
            groups: [movielist, movie]
