Myclapboard\ArtistBundle\Model\Role:
    exclusion_policy: ALL
    relations:
        -
            rel: movie
            href: 
                route: myclapboard_movie_get_movie
                parameters:
                    id: expr(object.getMovie().getId())
                absolute: true
            exclusion:
                groups: [cast]
    properties:
        artist:
            expose: true
            groups: [movieList, movie]
        movie:
            expose: true
            groups: [artist]
        awards:
            expose: true
            groups: [artist]
