Myclapboard\ArtistBundle\Model\Artist:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [movielist, movie, artistList, artist]
        slug:
            expose: true
            groups: [movielist, movie, artistList, artist]
        firstName:
            expose: true
            groups: [movielist, movie, artistList, artist]
        lastName:
            expose: true
            groups: [movielist, movie, artistList, artist]
        birthday:
            expose: true
            groups: [artistList, artist]
        birthplace:
            expose: true
            groups: [artistList, artist]
        biography:
            expose: true
            groups: [artistList, artist]
        photo:
            expose: true
            groups: [movielist, movie, artistList, artist]
        actors:
            expose: true
            groups: [artist]
        directors:
            expose: true
            groups: [artist]
        writers:
            expose: true
            groups: [artist]
        images:
            expose: true
            groups: [artist]
