Myclapboard\ArtistBundle\Model\Artist:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href: 
                route: myclapboard_artist_get_artist
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [movieList, movie, artistList, artist, role]
        -
            rel: movies
            href: 
                route: myclapboard_artist_get_artist_movies
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [artistList, artist]
        -
            rel: awards
            href: 
                route: myclapboard_artist_get_artist_awards
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [artistList, artist, role]
        -
            rel: images
            href: 
                route: myclapboard_artist_get_artist_images
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [artistList, artist]
    properties:
        id:
            expose: true
            groups: [movieList, movie, artistList, artist]
        slug:
            expose: true
            groups: [movieList, movie, artistList, artist]
        firstName:
            expose: true
            groups: [movieList, movie, artistList, artist]
        lastName:
            expose: true
            groups: [movieList, movie, artistList, artist]
        birthday:
            expose: true
            groups: [artistList, artist]
        birthplace:
            expose: true
            groups: [artistList, artist]
        biography:
            expose: true
            groups: [artistList, artist]
        photo:
            expose: true
            groups: [movieList, movie, artistList, artist]
        actors:
            expose: true
            groups: [actor]
        directors:
            expose: true
            groups: [director]
        writers:
            expose: true
            groups: [writer]
        images:
            expose: true
            groups: []
