Myclapboard\MovieBundle\Entity\Image:
    type: entity
    table: MovieImage
    id:
        name:
            type: string
            length: 100
    manyToOne:
        movie:
            targetEntity: Myclapboard\MovieBundle\Model\Interfaces\MovieInterface
    lifecycleCallbacks:
        postRemove: [removeUpload]
