# This file belongs to myClapboard.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Myclapboard\MovieBundle\Entity\Movie:
    type: entity
    gedmo:
        translation:
            entity: Myclapboard\MovieBundle\Entity\MovieTranslation
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        slug:
            type: string
            length: 100
        title:
            type: string
            length: 50
        duration:
            type: integer
        releaseDate:
            type: datetime
        storyline:
            type: string
            length: 2000
            nullable: true
        producer:
            type: string
            length: 100
            nullable: true
        website:
            type: string
            nullable: true
        poster:
            type: string
            length: 100
            nullable: true
    lifecycleCallbacks:
        postLoad: [calculateScore]
    oneToMany:
        actors:
            targetEntity: Myclapboard\ArtistBundle\Entity\Actor
            mappedBy: movie
            cascade: ["persist", "remove"]
            joinColumn:
                name: movie_id
                referencedColumnName: id
                onDelete: cascade
        directors:
            targetEntity: Myclapboard\ArtistBundle\Entity\Director
            mappedBy: movie
            cascade: ["persist", "remove"]
            joinColumn:
                name: movie_id
                referencedColumnName: id
                onDelete: cascade
        writers:
            targetEntity: Myclapboard\ArtistBundle\Entity\Writer
            mappedBy: movie
            cascade: ["persist", "remove"]
            joinColumn:
                name: movie_id
                referencedColumnName: id
                onDelete: cascade
        awards:
            targetEntity: Myclapboard\AwardBundle\Model\Interfaces\AwardWonInterface
            mappedBy: movie
            cascade: ["persist", "remove"]
            joinColumn:
                name: movie_id
                referencedColumnName: id
                onDelete: cascade
        images:
            targetEntity: Myclapboard\MovieBundle\Model\Interfaces\ImageInterface
            mappedBy: movie
            cascade: ["persist", "remove"]
        translations:
            targetEntity: Myclapboard\MovieBundle\Entity\MovieTranslation
            mappedBy: object
            cascade: ["persist", "remove"]
        ratings:
            targetEntity: Myclapboard\UserBundle\Model\Interfaces\RatingInterface
            mappedBy: movie
            fetch: EXTRA_LAZY
            cascade: ["persist", "remove"]
            joinColumn:
                name: movie_id
                referencedColumnName: id
                onDelete: cascade
        reviews:
            targetEntity: Myclapboard\UserBundle\Model\Interfaces\ReviewInterface
            mappedBy: movie
            cascade: ["persist", "remove"]
            joinColumn:
                name: movie_id
                referencedColumnName: id
                onDelete: cascade
    manyToOne:
        country:
            targetEntity: JJs\Bundle\GeonamesBundle\Entity\Country
    manyToMany:
        genres:
            targetEntity: Myclapboard\MovieBundle\Model\Interfaces\GenreInterface
            joinTable:
                name: MovieGenre
                joinColumns:
                    movie_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    genre_id:
                        referencedColumnName: id
