parameters:
    myclapboard_award.class.award: Myclapboard\AwardBundle\Entity\Award
    myclapboard_award.class.awardWon: Myclapboard\AwardBundle\Entity\AwardWon
    myclapboard_award.class.category: Myclapboard\AwardBundle\Entity\Category

services:
    # Managers
    myclapboard_award.manager.award:
        class: Myclapboard\AwardBundle\Manager\AwardManager
        arguments: ['@doctrine', '%myclapboard_award.class.award%']
    myclapboard_award.manager.awardWon:
        class: Myclapboard\AwardBundle\Manager\AwardWonManager
        arguments: ['@doctrine', '%myclapboard_award.class.awardWon%']
    myclapboard_award.manager.category:
        class: Myclapboard\AwardBundle\Manager\CategoryManager
        arguments: ['@doctrine', '%myclapboard_award.class.category%']

    # Commands
    myclapboard_award.command_awards:
        class: Myclapboard\AwardBundle\Command\LoadAwardsCommand
        calls:
            - [setContainer, ['@service_container'] ]
    myclapboard_award.command_awardsWon:
        class: Myclapboard\AwardBundle\Command\LoadAwardsWonCommand
        calls:
            - [setContainer, ['@service_container'] ]
    myclapboard_award.command_categories:
        class: Myclapboard\AwardBundle\Command\LoadCategoriesCommand
        calls:
            - [setContainer, ['@service_container'] ]
