#myclapboard_artist_artists:
#    type: rest
#    resource: Myclapboard\ArtistBundle\Controller\ArtistController

myclapboard_artist_get_artist:
    type: rest
    pattern:  /artists/{id}
    defaults: {_controller: MyclapboardArtistBundle:Artist:getArtist }
    requirements:
        _method: GET
