Filmboot\AwardBundle\Entity\Award:
    type: entity
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 50
        year:
            type: integer
        category:
            type: string
            length: 100
