Myclapboard\UserBundle\Entity\AccessToken:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: Myclapboard\UserBundle\Entity\Client
            joinColumn:
                nullable: false
        user:
            targetEntity: Myclapboard\UserBundle\Entity\User
