# This file belongs to myClapboard.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Myclapboard\UserBundle\Entity\User:
    type: entity
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        firstName:
            type: string
            length: 100
            nullable: true
        lastName:
            type: string
            length: 100
            nullable: true
        mobile:
            type: string
            length: 20
            nullable: true
        phone:
            type: string
            length: 20
            nullable: true
        birthday:
            type: datetime
            nullable: true
        gender:
            type: GenderEnum
            nullable: true
        apiKey:
            type: string
            length: 50
            nullable: true
        locale:
            type: string
            length: 6
        createdAt:
            type: datetime
        cookiesAccepted:
            type: boolean
    manyToOne:
        location:
            targetEntity: JJs\Bundle\GeonamesBundle\Entity\City
    oneToMany:
        ratings:
            targetEntity: Myclapboard\UserBundle\Model\Interfaces\RatingInterface
            mappedBy: user
            cascade: ["persist", "remove"]
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: cascade
        reviews:
            targetEntity: Myclapboard\UserBundle\Model\Interfaces\ReviewInterface
            mappedBy: user
            cascade: ["persist", "remove"]
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: cascade
